### ISSUE TITLE
Prisma Studio incorrect API subpath routes

### ISSUE THREAD

**Issue by bartosjiri** [prisma/studio#1052]
### Bug description

Similar to https://github.com/prisma/studio/issues/1025, when launching/hosting Prisma Studio on a subpath, the Studio app fails to launch because of a non-recoverable error:
```
Error in HTTP Request (Status: 404)
{}
```

From observing network logs, application scripts requests seem to respect the subpath, however the API endpoint requests ignore the subpath:
![Application script request example](https://i.imgur.com/t9I4P5X.png)
![API request example](https://i.imgur.com/KuwFvw7.png)

Launching the Studio without a subpath works well. 
Also, manual requests (e.g. from Postman) to the API endpoint with the subpath works as intended:
![Manual API request example](https://i.imgur.com/b27gOJk.png)

### How to reproduce

Host Prisma Studio on a subpath instead of root of hostname.

Docker Compose + Traefik example, hosting Prisma Studio at `http://localhost/prisma-studio/`:
1. Create `docker-compose.yml` file with Traefik subpath configuration:
    ```yml
    version: "3.7"
    
    services:
      traefik:
        image: "traefik:v2.4"
        container_name: traefik
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "./traefik.yml:/etc/traefik/traefik.yml:ro"
        ports:
          - "80:80"
          - "8080:8080"
        labels:
          - "traefik.enable=true"
          - "traefik.port=8080"
          - "traefik.http.routers.traefik-dashboard.entrypoints=web"
          - "traefik.http.routers.traefik-dashboard.service=api@internal"
        networks:
          - traefik-proxy
      db:
        # ...configuration for your DB
      api:
        # ...configuration for your server application with Prisma
        expose:
          - 5555
        labels:
          - "traefik.http.routers.prisma-studio.entrypoints=web"
          - "traefik.http.routers.prisma-studio.service=prisma-studio"
          - "traefik.http.routers.prisma-studio.rule=PathPrefix(`/prisma-studio{regex:$$|/.*}`)"
          - "traefik.http.routers.prisma-studio.middlewares=prisma-studio-stripprefix@docker"
          - "traefik.http.middlewares.prisma-studio-stripprefix.stripprefix.prefixes=/prisma-studio"
          - "traefik.http.middlewares.prisma-studio-stripprefix.stripprefix.forceslash=true"
          - "traefik.http.services.prisma-studio.loadbalancer.server.port=5555"
        networks:
          - traefik-proxy
    
    networks:
      traefik-proxy:
        name: "traefik-proxy"
    ```
2. Create `traefik.yml` with additional Traefik configuration:
    ```yml
    entryPoints:
      web:
        address: ":80"
    
    api:
      dashboard: true
      debug: true
      insecure: true
    
    providers:
      docker:
        endpoint: "unix:///var/run/docker.sock"
        network: traefik-proxy
        watch: true
        exposedByDefault: false
    ```
3. Create your server application with Prisma: _(individual setup)_
4. Launch the platform stack and start Prisma Studio:
    ```
    docker compose up --build -d
    docker ps
    docker exec -it <server container ID> /bin/sh
    npx prisma studio
    ```
5. Navigate to `http://localhost/prisma-studio/` in your browser.

### Expected behavior

Prisma Studio should make requests to API endpoints through relative paths to respect hosting on subpaths.

### Prisma information

prisma: 4.6.0
@prisma/client: 4.6.0
Studio: 0.476.0

### Environment & setup

_(unrelated)_
