### ISSUE TITLE
Prisma Studio Fatal Error Under Docker-compose: "You don't have any models defined in your schema.prisma"

### ISSUE THREAD

**Issue by satotory** [prisma/studio#1123]
- prisma.schema is in ./prisma
- prisma migrations works fine, connected with db
- all working fine except **Prisma Studio**

1. Prisma version (`npx prisma -v`):
```
prisma                  : 4.14.1
@prisma/client          : 4.14.1
Current platform        : linux-musl-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at node_modules/@prisma/engines/migration-engine-linux-musl-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```
2. Logs from Developer Tools Console or Command line, if any:
```
2023-05-27 14:41:55 Unable to get DMMF from Prisma Client:  Error: 
2023-05-27 14:41:55 You don't have any models defined in your schema.prisma, so nothing will be generated.
2023-05-27 14:41:55 You can define a model like this:
2023-05-27 14:41:55 
2023-05-27 14:41:55 model User {
2023-05-27 14:41:55   id    Int     @id @default(autoincrement())
2023-05-27 14:41:55   email String  @unique
2023-05-27 14:41:55   name  String?
2023-05-27 14:41:55 }
2023-05-27 14:41:55 
2023-05-27 14:41:55 More information in our documentation:
2023-05-27 14:41:55 https://pris.ly/d/prisma-schema
2023-05-27 14:41:55 
2023-05-27 14:41:55     at getGenerators (/node_modules/prisma/build/index.js:45542:15)
2023-05-27 14:41:55     at async $fc77884679bbcc28$export$569332143708bf93 (/node_modules/prisma/build/index.js:114218:28)
2023-05-27 14:41:55     at async Object.getDMMF (/node_modules/prisma/build/index.js:114279:39)
2023-05-27 14:41:55     at async Object.respond (/node_modules/prisma/build/index.js:114497:37)
2023-05-27 14:41:55     at async /node_modules/prisma/build/index.js:114664:26
```

3. Does the issue persist even after updating to the latest `prisma` CLI dev version? (`npm i -D prisma@dev`): **yes**
```
prisma                  : 4.15.0-dev.85
@prisma/client          : 4.14.1
```
4. Prisma schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(autoincrement())
  email String @unique
  name String?
  role Role @default(USER)
  password String
}

enum Role {
  USER
  SELLER
}
```
5. Docker-compose file:
      docker-compose.yaml
    ```
    prisma-studio:
        container_name: prisma-studio
        image: timothyjmiller/prisma-studio:latest
        restart: unless-stopped
        env_file:
         - .env
        ports:
          - ${PRISMA_STUDIO_PORT}:5555
    
      postgres:
        container_name: prisma-postgres
        image: postgres:alpine
        restart: always
        env_file:
         - .env
        ports:
          - ${POSTGRES_PORT}:5432
        volumes:
          - ${POSTGRES_PATH}/${PROJECT_NAME}/${POSTGRES_DATABASE}/:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
    ```
    .env
    ```
    COMPOSE_PROJECT_NAME="prismanest"
    PROJECT_NAME="prismanest"
    POSTGRES_DATABASE="app"
    POSTGRES_HOST="postgres"
    POSTGRES_USERNAME="postgres"
    POSTGRES_PASSWORD="secret"
    POSTGRES_PORT="5432"
    PRISMA_STUDIO_PORT="5555"
    POSTGRES_PATH="/postgres"
    ```
I tried to find similar errors but didn't find anything similar. Maybe i should define schema.prisma file path for Prisma Studio?

**Comment by janpio** [comment]
Looking at the repo of the container, it looks to me that the schema is actually filled on startup of the container via running `db pull`: [`ENTRYPOINT ["/bin/sh", "prisma-introspect.sh"]`](https://github.com/timothymiller/docker-prisma-studio/blob/6727ebd063c4cd0a595322f3b4684d5f0670bf79/Dockerfile#L25). Maybe that fails for you, leading to an empty schema file.

**Comment by satotory** [comment]
https://github.com/prisma/studio/issues/296#issuecomment-558615808 - this helped me a little bit. 

rewrote prisma-studio container:

- docker-compose.yaml prisma-studio container:
    ```
    prisma-studio:
        links:
          - postgres
        depends_on:
          - postgres
        container_name: prisma-studio
        ports:
          - '5555:5555'
        build:
          context: docker/prismaStudio
          dockerfile: Dockerfile
        environment:
          DATABASE_URL: ${DATABASE_URL}
        volumes:
          - ./prisma:/app/prisma
    ```

- docker/prismaStudio/Dockerfile:

    ```Dockerfile
    FROM node:18-alpine
    
    RUN mkdir /app
    WORKDIR /app
    
    RUN npm install prisma --save-dev
    
    RUN npm init -y
    
    CMD [ "npx", "prisma", "studio" ]
    ```
> It can be better, but for local education dev, for me especially - it's ok
