### ISSUE TITLE
Docker and prisma studio

### ISSUE THREAD

**Issue by FrancoisVeauvy** [prisma/studio#296]
After upgrading to prisma2 preview 17, I modified my Dockerfile in order to assure that @prisma/photon is installed.  When I dockerize my app I got this error when I try to open prisma studio on http://localhost:5555

**Error dump**
Cannot destructure property `dmmf` of 'undefined' or 'null'.

**Stacktrace**
TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
    at connect (/usr/local/lib/node_modules/prisma2/build/photon-worker.js:44:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process.<anonymous> (/usr/local/lib/node_modules/prisma2/build/photon-worker.js:9:18)

**Comment by madebysid** [comment]
@FrancoisVeauvy I think I know what might be causing this. Could you share your Dockerfile if possible?
Have you tried using Photon via a script as well? Does that work?

**Comment by FrancoisVeauvy** [comment]
@madebysid : of course, I'll be glad to.

`docker-compose.yml`

```yml
version: '3.7'
services:
  postgres:
    container_name: postgres
    ports:
      - '5432:5432'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'prisma'
      POSTGRES_USER: 'prisma'
      POSTGRES_PASSWORD: 'prisma'
    volumes:
      - postgres:/var/lib/postgres
  prisma:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - /app/prisma
  backend:
    links:
      - postgres
    depends_on:
      - postgres
      - prisma
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - POSTGRES_URL=${POSTGRES_URL}
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: ${BACKEND_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres:
```

`Dockerfile` (Prisma)

```Dockerfile
FROM node:12.13.0
RUN npm install -g --unsafe-perm prisma2

RUN mkdir /app
WORKDIR /app

COPY ./ ./prisma/

RUN npm init -y
RUN npm install @prisma/photon

CMD [ "prisma2", "dev" ]
```

`Dockerfile` (Backend)

```Dockerfile
FROM node:12.13.0
RUN npm install -g --unsafe-perm prisma2

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

ARG POSTGRES_URL
ENV POSTGRES_URL "$POSTGRES_URL"

COPY src ./src/

RUN npm install --unsafe-perm
RUN prisma2 generate

CMD [ "npm", "run", "dev" ]
```

**Comment by himerus** [comment]
I'm seeing a similar result when using Docksal as my docker/docker-compose wrapper. 

Nothing special in the setup, but when I run my `prisma2 dev` command, the following is output during the generation. 

```
Failed to generate Photon client: Error: Error: Command failed with ENOENT: /var/www/apps/api/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn /var/www/apps/api/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT
    at Object.<anonymous> (/var/www/apps/api/node_modules/prisma2/build/index.js:121706:19)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/apps/api/node_modules/prisma2/build/index.js:121635:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error starting Photon: TypeError: Cannot destructure property `dmmf` of 'undefined' or 'null'.
```

After this error hits the logs, the script continues on and says Database was migrated successfully and that Photon.js was generated and my application works, just not the Studio.

**Comment by madebysid** [comment]
Hey everyone, we just pushed out preview017.2, which fixes an issue with prisma2 & paths on Linux. This was quite possibly related, because I'm able to view Studio on Docker now.

@FrancoisVeauvy The Docker setup you're using was pretty complex, so I set up an extremely primitive one with SQLite and `prisma2@latest` and it seems to be working. Please retry and let me know if this is resolved for you as well. If not, I'll attempt to reproduce your setup and dig deeper.

Here's the setup I used:

docker-compose:
```
version: "3.7"
services:
  prisma:
    container_name: prisma
    ports:
      - "5555:5555"
    build:
      context: prisma
      dockerfile: Dockerfile
```

prisma/Dockerfile:
```
FROM node:12.13.0
RUN npm install -g --unsafe-perm prisma2

RUN mkdir /app
WORKDIR /app

COPY ./* ./prisma/

RUN npm init -y
RUN npm install @prisma/photon

CMD [ "prisma2", "studio" ]

EXPOSE 5555/tcp
```
